### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by vyorkin** [router5/redux-router5#1]
there is a broken link here: https://github.com/router5/redux-router5#with-react

```
you can use withContext() from recompose <<
```

I've found only [this recompose](https://github.com/acdlite/recompose) and as I can see there is no `withContext()` function, so I don't know how to fix this

**Comment by troch** [comment]
@vyorkin as mentioned in the chat, I fixed it. Sorry about the delay, I wasn't watching that repo :/

**Comment by vyorkin** [comment]
cool! thanks @troch !
