### ISSUE TITLE
routeNodeSelector vs routeNode

### ISSUE THREAD

**Issue by klimashkin** [router5/redux-router5#5]
It's not quite clear from the docs whether `routeNodeSelector` or `routeNode` should be used. 
Or can/should they be used together?

For example, `routeNodeSelector` doesn't provide `router` from context to construct href etc

**Comment by troch** [comment]
`routeNode` is part of `react-router5` and to be used with `router5-listeners` plugin to bind to route node changes.

When you use redux, your unique source of truth becomes your store. `routeNodeSelector` is a memoized selector and designed to be used with `connect` (see https://github.com/reactjs/reselect, also `routeNodeSelector` does not depend on reselect).

`routeNodeSelector` "replaces" `routeNode`, but it is just a selector so it doesn't grab your router instance from context to inject it into props.
