### ISSUE TITLE
Update router5.transition-path

### ISSUE THREAD

**Issue by klimashkin** [router5/redux-router5#8]
Now with `router5 4.1.1` and `redux-router5` we have two versions of `router5.transition-path`, so I still have https://github.com/router5/router5/issues/85 error

**Comment by troch** [comment]
Yep, fixed in 4.2.1

**Comment by klimashkin** [comment]
Btw, on `router5 4.1.0` and `redux-router5 4.2.0` when I dispatch navigation action, I have two error messages

```
[router5.transition-path] Some states are missing metadata, reloading all segments
[router5.transition-path] Some states are missing metadata, reloading all segments
```

If I update to `router5 4.1.1` and `redux-router5 4.2.0` I see only one.

Does that mean that we call `transition-path` twice somewhere?

**Comment by troch** [comment]
You shouldn't see any normally.

**Comment by troch** [comment]
Are you using `routeNodeSelector` the right way? i.e. `export default connect(state => routeNodeSelector(''))(Root);` and not `export default connect(routeNodeSelector(''))(Root);`?

**Comment by klimashkin** [comment]
I see, that's because I use
`const {toActivate} = transitionPath(toState, fromState);`
In my middleware get activated routes.

And it's calculated again each time.
Is it possible to have transition path as a parameter to middlewares to not compute it twice?

**Comment by troch** [comment]
> Is it possible to have transition path as a parameter to middlewares to not compute it twice?

Can look into that

It should not warn though if states have `meta.params` properties

**Comment by klimashkin** [comment]
npm: `No compatible version found: redux-router5@4.2.1` so far

**Comment by troch** [comment]
Maybe a slow propagation. https://www.npmjs.com/package/redux-router5 shows the latest version 4.2.1. If there are issues, I'll look into them tomorrow.

**Comment by klimashkin** [comment]
npm updated
