### ISSUE TITLE
Can't write shrinkwrap if I don't use immutable.js

### ISSUE THREAD

**Issue by klimashkin** [router5/redux-router5#9]
Hi! 
I don't use immutable.js in project and after updating redux-router5 I can't execute `npm shrinkwrap`
`redux-router5@4.2.1 requires a peer of immutable@^3.0.0 but none was installed.`

Did you mean to put immutable.js in package.json as `optionalDependencies` instead of peer in 8764ce6edaa81f91800602f5c57788a673fe9046? 
сс @Nihaux

**Comment by troch** [comment]
Yes, `optionalDependencies` make more sense

**Comment by troch** [comment]
Released a patch with immutable in optional dependencies (4.2.2)
